# Numpy

In [1]:
!pip install numpy 

In [3]:
import numpy as np

## Create array using numpy
## Create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # Show dim 

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 column 

array([[1, 2, 3, 4, 5]])

In [5]:
# 2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Identity Matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Attributes in numpy array
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimension",arr.ndim)
print("Size (number of element)",arr.size)
print("Data Type",arr.dtype)
print("Item size (in bytes)",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension 2
Size (number of element) 6
Data Type int64
Item size (in bytes) 8


In [12]:
## numpy vectorized operations 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition 
print("Addition",arr1 + arr2)
# Element wise substrction
print("Substrction", arr1 - arr2)
# Element wise multiplication 
print("multiplication", arr1 * 2)


Addition [11 22 33 44 55]
Substrction [ -9 -18 -27 -36 -45]
multiplication [ 2  4  6  8 10]


In [13]:
# Universal Funtion --> Apply over array
arr =  np.array([2,4,5,6,7])
## Square root
print(np.sqrt(arr))

[1.41421356 2.         2.23606798 2.44948974 2.64575131]


In [14]:
# Exponential 
print(np.exp(arr))


[   7.3890561    54.59815003  148.4131591   403.42879349 1096.63315843]


In [15]:
# sine
print("Sine",np.sin(arr))

# Natural log
print("Natural log",np.log(arr))

Sine [ 0.90929743 -0.7568025  -0.95892427 -0.2794155   0.6569866 ]
Natural log [0.69314718 1.38629436 1.60943791 1.79175947 1.94591015]


In [16]:
## array slicing and Indexing 
arr = np.array([[1,2,3,4,5],[11,2,3,4,5],[1,2,3,4,5]])
print("Array: \n" ,arr)

Array: 
 [[ 1  2  3  4  5]
 [11  2  3  4  5]
 [ 1  2  3  4  5]]


In [18]:
arr[0]

array([1, 2, 3, 4, 5])

In [22]:
print(arr[0][0])

1


In [27]:
print(arr[1][0])

11


In [29]:
print(arr[1:,0:])

[[11  2  3  4  5]
 [ 1  2  3  4  5]]


In [32]:
print(arr[0:2,2:])

[[3 4 5]
 [3 4 5]]


In [33]:
# Modify array elements 
arr[0,0] = 100 
print(arr)

[[100   2   3   4   5]
 [ 11   2   3   4   5]
 [  1   2   3   4   5]]


In [34]:
arr[1:] = 100 # first element till the last 
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [35]:
## Statistical Concepts -- Normalization 
## To have a mean of 0  and Standard deviation of 1 
data = np.array([1,2,3,4,5])

# Calculate the mean and Standerd deviation 
mean = np.mean(data)
std_dev = np.std(data)

# Normalization 
normalized_Data = (data - mean) / std_dev
print("Normalized data :",normalized_Data)


Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [36]:
## Logical operations 
data =  np.array([1,2,3,4,5,6,7,8,9,10])
data > 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
data [data>5]

array([ 6,  7,  8,  9, 10])

In [39]:
data[(data>=5)&(data<=8)]

array([5, 6, 7, 8])